language: c
git:
  quiet: true
  depth: 1
os: linux
compiler:
- clang
- gcc
script:
- "./configure && make test"
- make distclean > /dev/null 2>&1
- mkdir build && cd build && ../configure && make test
- make distclean > /dev/null 2>&1
- cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=../libsbl
- make install
- cd ..
- mkdir .dpl
- tar zcvf .dpl/libsbl-`uname -s`-`uname -m`-$CC.tar.gz libsbl
jobs:
  include:
  - os: osx
    osx_image: xcode8
    compiler: gcc
    env:
    - CC=gcc-4.9
    - CXX=g++-4.9
  - os: windows
    script:
    - mkdir build
    - cd build
    - cmake .. -DCMAKE_INSTALL_PREFIX=../libsbl
    - '"C:/Program Files (x86)/Microsoft Visual Studio/2017/BuildTools/MSBuild/15.0/Bin/MSBuild.exe"
      -property:Configuration=Release INSTALL.vcxproj'
    - cd ..
    - mkdir .dpl
    - 7z a -tzip .dpl/libsbl-win-x86_64-msvc.zip libsbl
deploy:
  provider: releases
  api_key:
    secure: VJGWyJARhPjeXnKlReg2EAeOlg5FZ1ufpialfRomeNJT1xAdcSsHwgzESVj9djwbNQfzpteLYE7HK/2LDEkL3uPbCUdqS7oEL/hYU05zS6DtErupyNW7JjpieMeBbh/frC2K93PhNp3iGtdDsHIIsVdziX8QLooAghDD2s6kO4iNFYYx+BB0e0mw27S2w0anfhaXzhseq8GK6sXlRWgoN68GKFxm2yz1rwafZ9qMNPuaK2XhNwpfhgXGId5qrt692whqO+WKSdOM37OoULbUssoXifZyHFU0q5CoiARzZwu5gT5upK+RVLrIAfjApWM7rAvoj6jbiBYzmnjlzC8n7lxFbhlE69VBwpyRKFvxPRDjppVmGmwQ1vIqB1ztEeXx2OejMnpDzcwpWMyoltfowstpRNA8eS6AVmvlUU5LgVkndk9zceAG3gOMvJR55/I1orQpHm7XNWE0Md4pyj5OroxI0krYCkVGtF/TsEjTlbUkTuY0XOS59Ets84LmuDqyXCxNUCaQGH3x/U7/HspU3DNzGwF9JpB9QFNfZctV8o9T/AgX84X0JvDY3OJRd67XjE5/8adYTGSmXv/rKKh6kIdgHXm27MJCfsCVY8STrI03AJWxJl0VG+reaSULEuVJelcPsT9KWOSsF2ZME/dvSdLr2EFlOy+bcPEO7IlrsdQ=
  file: "*"
  skip_cleanup: true
  draft: true
  on:
    repo: myzhang1029/slib
    #tags: true
