language: c
git:
    quiet: true
    depth: 3

os: linux

compiler:
    - clang
    - gcc

jobs:
    include:
        # macOS GCC@4
        - os: osx
          env:
             - CC=gcc-4.9
             - CXX=g++-4.9"
        # Windows
        - os: windows
          script:
              - cmake . && nmake && nmake test
              - mkdir build && build
              - cmake .. && nmake && nmake test

script:
    - ./configure && make test
    - cmake . && make && make test
    - mkdir build && cd build && ../configure && make test
    - cmake .. && make && make test
