language: c
git:
    quiet: true
    depth: 3

os: linux

compiler:
    - clang
    - gcc

matrix:
    include:
        # macOS GCC@4
        - os: osx
          osx_image: xcode8
          env:
             - MATRIX_EVAL="CC=gcc-4.9 && CXX=g++-4.9"
        # Windows
        - os: windows

before_install:
    - eval "${MATRIX_EVAL}"

script:
    - ./configure && make test
    - cmake . && make && make test
    - mkdir build && cd build && ../configure && make test
    - cmake .. && make && make test
