language: c
git:
  quiet: true
  depth: 1
os: linux
compiler:
- clang
- gcc
script:
- cmake . -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=../libsbl
- make install
- make distclean
- ./configure.plain && make test
- make distclean > /dev/null 2>&1
- mkdir build && cd build
- ../configure.plain && make test
- make distclean > /dev/null 2>&1
jobs:
  include:
  - os: windows
    script:
    - mkdir build
    - cd build
    - cmake .. -DCMAKE_INSTALL_PREFIX=../libsbl
    - '"C:/Program Files (x86)/Microsoft Visual Studio/2017/BuildTools/MSBuild/15.0/Bin/MSBuild.exe"
      -property:Configuration=Release INSTALL.vcxproj'
