language: c
git:
    quiet: true
    depth: 3

os:
    - osx
    - linux

compiler:
    - clang
    - gcc

matrix:
    include:
        # Windows
        - os: windows
          script:
              - cmake . && nmake && nmake test
              - mkdir build && build
              - cmake .. && nmake && nmake test

before_install:
    - eval "${MATRIX_EVAL}"
    - ${CC} --version

script:
    - ./configure && make test
    - cmake . && make && make test
    - mkdir build && cd build && ../configure && make test
    - cmake .. && make && make test
