language: c
git:
    quiet: true
    depth: 3

os: linux

compiler:
    - clang
    - gcc

jobs:
    include:
        # macOS GCC@4
        - os: osx
          osx_image: xcode8
          compiler: gcc
          env:
             - CC=gcc-4.9
             - CXX=g++-4.9
        # Windows
        - os: windows
          script:
              - mkdir build
              - cd build
              - cmake ..
              - $MSBPATH/MSBuild.exe ALL_BUILD.vcxproj -property:Configuration=Debug
          env:
              - MSBPATH="/C/Program Files (x86)/Microsoft Visual Studio/2017/BuildTools/MSBuild/15.0/Bin"

script:
    - ./configure && make test
    - mkdir build && cd build && ../configure && make test
    - cmake .. && make && make test
