language: c
matrix:
    include:
        # Linux clang
        - os: linux
          addons:
              apt:
                  sources:
                      - ubuntu-toolchain-r-test
                      - llvm-toolchain-precise-3.8
                  packages:
                      - clang-3.8
                  env:
                      - MATRIX_EVAL="CC=clang-3.8 && CXX=clang++-3.8"
        # Linux GCC 
        - os: linux
          addons:
              apt:
                  sources:
                      - ubuntu-toolchain-r-test
                  packages:
                      g++-7
          env:
              - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
        # macOS GCC@4
        - os: osx
          osx_image: xcode8
          env:
              - MATRIX_EVAL="CC=gcc-4.9 && CXX=g++-4.9"
before_install:
    - eval "${MATRIX_EVAL}"
